version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    container_name: mcp_tutorial_data_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mcp_tutorial_data}
      POSTGRES_USER: ${POSTGRES_USER:-mcp_tutorial_data_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mcp_tutorial_data_db_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mcp_tutorial_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mcp_tutorial_data_db_user} -d ${POSTGRES_DB:-mcp_tutorial_data}"]
      interval: 10s
      timeout: 5s
      retries: 5
  chromadb:
    image: chromadb/chroma:1.1.1
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - mcp_tutorial_network


volumes:
  postgres_data:

networks:
  mcp_tutorial_network:
    driver: bridge