[project]
name = "vectordb-python-mcp-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
    "psycopg2>=2.9.11",
]
